import type { CapabilityDefinition } from "../../types/capability.js";

const EMPTY_SCHEMA = {
  type: "object",
  properties: {},
  additionalProperties: false,
} as const;

export function createDeclaredCapabilityCatalog(): CapabilityDefinition[] {
  return [
    {
      name: "calendar.read",
      domain: "secretario_operacional",
      category: "calendar",
      description: "Ler agendas, eventos próximos, períodos e conflitos de calendário.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      declaredOnly: true,
    },
    {
      name: "calendar.write",
      domain: "secretario_operacional",
      category: "calendar",
      description: "Criar, mover, renomear e remover eventos com confirmação controlada.",
      inputSchema: EMPTY_SCHEMA,
      risk: "medium",
      sideEffects: ["write", "schedule"],
      requiresApproval: true,
      integrationKey: "google_workspace",
      declaredOnly: true,
    },
    {
      name: "tasks.read",
      domain: "secretario_operacional",
      category: "tasks",
      description: "Ler listas e tarefas do Google Tasks.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "google_workspace",
      declaredOnly: true,
    },
    {
      name: "tasks.write",
      domain: "secretario_operacional",
      category: "tasks",
      description: "Criar, atualizar e remover tarefas com execução controlada.",
      inputSchema: EMPTY_SCHEMA,
      risk: "medium",
      sideEffects: ["write"],
      requiresApproval: true,
      integrationKey: "google_workspace",
      declaredOnly: true,
    },
    {
      name: "weather.lookup",
      domain: "secretario_operacional",
      category: "weather",
      description: "Consultar clima atual e previsão curta.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      declaredOnly: true,
    },
    {
      name: "web.search",
      domain: "orchestrator",
      category: "web",
      description: "Pesquisar na web e sintetizar resultados recentes.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      declaredOnly: true,
    },
    {
      name: "maps.geocode",
      domain: "secretario_operacional",
      category: "maps",
      description: "Resolver endereço/local a partir de texto usando Places/Geocoding.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "google_maps",
      declaredOnly: true,
    },
    {
      name: "maps.places_search",
      domain: "secretario_operacional",
      category: "maps",
      description: "Buscar lugares próximos, restaurantes, hotéis e pontos de interesse.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "google_maps",
      declaredOnly: true,
    },
    {
      name: "maps.route",
      domain: "secretario_operacional",
      category: "maps",
      description: "Calcular rota entre origem e destino.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "google_maps",
      declaredOnly: true,
    },
    {
      name: "maps.distance",
      domain: "secretario_operacional",
      category: "maps",
      description: "Calcular distância e duração de deslocamento.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "google_maps",
      declaredOnly: true,
    },
    {
      name: "maps.tolls",
      domain: "secretario_operacional",
      category: "maps",
      description: "Estimar pedágios em uma rota.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "google_maps",
      declaredOnly: true,
    },
    {
      name: "travel.flights",
      domain: "secretario_operacional",
      category: "travel",
      description: "Pesquisar e comparar opções de passagens aéreas.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "web_search",
      experimental: true,
      declaredOnly: true,
    },
    {
      name: "travel.buses",
      domain: "secretario_operacional",
      category: "travel",
      description: "Pesquisar e comparar opções de ônibus/rodoviário.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "web_search",
      experimental: true,
      declaredOnly: true,
    },
    {
      name: "travel.hotels",
      domain: "secretario_operacional",
      category: "travel",
      description: "Pesquisar hospedagem e opções de hotel/pousada.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "web_search",
      experimental: true,
      declaredOnly: true,
    },
    {
      name: "messaging.monitor",
      domain: "secretario_operacional",
      category: "messaging",
      description: "Monitorar canais externos e gerar alertas operacionais.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "whatsapp_monitor",
      declaredOnly: true,
    },
    {
      name: "messaging.reply_draft",
      domain: "secretario_operacional",
      category: "messaging",
      description: "Preparar rascunho de resposta para canais monitorados.",
      inputSchema: EMPTY_SCHEMA,
      risk: "medium",
      sideEffects: ["write"],
      requiresApproval: true,
      integrationKey: "whatsapp_monitor",
      declaredOnly: true,
    },
    {
      name: "visual.schedule_import",
      domain: "secretario_operacional",
      category: "visual",
      description: "Importar agenda a partir de print/PDF com rascunho antes de gravar.",
      inputSchema: EMPTY_SCHEMA,
      risk: "medium",
      sideEffects: ["read", "schedule"],
      requiresApproval: true,
      integrationKey: "visual_import",
      declaredOnly: true,
    },
    {
      name: "visual.profile_analysis",
      domain: "social_media",
      category: "visual",
      description: "Analisar material visual de perfil/social com fluxo guiado.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      integrationKey: "visual_analysis",
      experimental: true,
      declaredOnly: true,
    },
    {
      name: "identity.read",
      domain: "orchestrator",
      category: "identity",
      description: "Ler perfil de identidade operacional do usuário.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      declaredOnly: true,
    },
    {
      name: "memory.learned_preferences.read",
      domain: "orchestrator",
      category: "memory",
      description: "Listar aprendizados e preferências aprendidas do Atlas.",
      inputSchema: EMPTY_SCHEMA,
      risk: "low",
      sideEffects: ["read"],
      requiresApproval: false,
      declaredOnly: true,
    },
    {
      name: "memory.learned_preferences.write",
      domain: "orchestrator",
      category: "memory",
      description: "Registrar ou desativar aprendizados operacionais do Atlas.",
      inputSchema: EMPTY_SCHEMA,
      risk: "medium",
      sideEffects: ["write"],
      requiresApproval: false,
      declaredOnly: true,
    },
  ];
}
